name: Deploy Riot API Service

on:
  push:
    branches: [ main ]
    paths:
      - 'riot-api/**'
      - '.github/workflows/deploy-riot-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Build and push Docker image
      run: |
        cd riot-api
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/gg-edge-riot-api
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy gg-edge-riot-development-api \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/gg-edge-riot-api \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --update-secrets=RIOT_API_KEY=riot-api-key:latest
